# Generated by Django 4.0.4 on 2022-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=100)),
                ('pub_data', models.DateField()),
                ('isbn', models.CharField(max_length=17)),
                ('page_count', models.PositiveSmallIntegerField()),
                ('cover_url', models.URLField()),
                ('language', models.CharField(max_length=3)),
            ],
        ),
    ]
