# Generated by Django 4.0.4 on 2022-04-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_data',
            new_name='pub_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=300, primary_key=True, serialize=False),
        ),
    ]
