# Generated by Django 4.0.4 on 2022-04-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_alter_book_author_alter_book_cover_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
