# Generated by Django 4.0.4 on 2022-04-14 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0010_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(13), django.core.validators.RegexValidator(message='Podaj numer ISBN składający się z cyfr bez znaków', regex='^[0-9]*$')]),
        ),
    ]
